title = "seedshare"
baseURL = "https://seedshare.io/"
tags = ["portfolio", "web developer", "blog", "programming"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-132818094-1"
pygmentsStyle = "manni"
pygmentsCodefences = "true"

[Params]
  tagline = "technology to inspire"
  author = "Kevin Caravaggio"
  description = "Software Engineer in Seattle developing cloud-powered enterprise services"
  logoBig = "/images/seedshare-banner.jpg"
  logoSmall = "/images/seedshare-symbol.png"
  favicon = "/images/seedshare-favicon.png"
  opengraphImage = "/images/osprey.png"
  twitter = "kevvurs"
  linkedin = "kevin-caravaggio"
  github = "kevvurs"
  facebook = ""
  email = "hello@seedshare.io"
  googleTagManger = " "
  highlightJS = false
  copyright = true
  credit = true
  customCSS = false
  cacheBustCSS = false
  cacheBustJS = false
  ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Featured"
    url  = "/#featured"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
